name       : tint2
version    : 16.7
release    : 12
source     :
    - git|https://gitlab.com/o9000/tint2 : 16.7
license    : GPL-2.0-or-later
component  : desktop
summary    : A lightweight panel/taskbar for Linux and BSD
description: |
    tint2 is a simple panel/taskbar made for modern X window managers
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(imlib2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xrandr)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
